// Class L2Parser, my own version of T59 language grammar analyzer
// Transforms a stream of L2Token into a stream of L2Statement
//
// 2025-11-21   PV      First version

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace T59v5;

struct Inst
{
    public string s { get; set; }       // Syntax
    public bool i { get; set; }         // Invertible
    public int m { get; set; }          // Indirect merged code
}

internal class L2Parser
{
    static Dictionary<int, Inst> tinst = new();

    static L2Parser() 
    {
        // Build dictionary of instructions attributes, generated by Excel
        // Doesn't include extra instructions I123_e_power_x and I128_10_power_x, we'll see later if they need to be included or managed directly in parser code
        tinst.Add(Vocab.I10_e_prime, new Inst { s = "a" });
        tinst.Add(Vocab.I11_a, new Inst { s = "a" });
        tinst.Add(Vocab.I12_b, new Inst { s = "a" });
        tinst.Add(Vocab.I13_c, new Inst { s = "a" });
        tinst.Add(Vocab.I14_d, new Inst { s = "a" });
        tinst.Add(Vocab.I15_e, new Inst { s = "a" });
        tinst.Add(Vocab.I16_a_prime, new Inst { s = "a" });
        tinst.Add(Vocab.I17_b_prime, new Inst { s = "a" });
        tinst.Add(Vocab.I18_c_prime, new Inst { s = "a" });
        tinst.Add(Vocab.I19_d_prime, new Inst { s = "a" });
        tinst.Add(Vocab.I20_2nd_clear, new Inst { s = "a" });
        tinst.Add(Vocab.I22_invert, new Inst { s = "a" });
        tinst.Add(Vocab.I23_ln, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I24_correct_entry, new Inst { s = "a" });
        tinst.Add(Vocab.I25_clear, new Inst { s = "a" });
        tinst.Add(Vocab.I27_2nd_invert, new Inst { s = "a" });
        tinst.Add(Vocab.I28_log, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I29_clear_program, new Inst { s = "a" });
        tinst.Add(Vocab.I30_tan, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I32_exchange_x_and_t, new Inst { s = "a" });
        tinst.Add(Vocab.I33_square, new Inst { s = "a" });
        tinst.Add(Vocab.I34_square_root, new Inst { s = "a" });
        tinst.Add(Vocab.I35_reciprocal, new Inst { s = "a" });
        tinst.Add(Vocab.I36_program, new Inst { s = "di", m = 62 });
        tinst.Add(Vocab.I37_polar_to_rectangular, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I38_sin, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I39_cos, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I42_store, new Inst { s = "di", m = 72 });
        tinst.Add(Vocab.I43_recall, new Inst { s = "di", m = 73 });
        tinst.Add(Vocab.I44_sum, new Inst { s = "di", i = true, m = 74 });
        tinst.Add(Vocab.I45_power, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I47_clear_memory, new Inst { s = "a" });
        tinst.Add(Vocab.I48_exchange, new Inst { s = "di", m = 63 });
        tinst.Add(Vocab.I49_product, new Inst { s = "di", i = true, m = 64 });
        tinst.Add(Vocab.I50_absolute, new Inst { s = "a" });
        tinst.Add(Vocab.I52_exponent, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I53_left_parenthesis, new Inst { s = "a" });
        tinst.Add(Vocab.I54_right_parenthesis, new Inst { s = "a" });
        tinst.Add(Vocab.I55_divide, new Inst { s = "a" });
        tinst.Add(Vocab.I57_engineering, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I58_fix, new Inst { s = "di", i = true });
        tinst.Add(Vocab.I59_integer, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I60_degrees, new Inst { s = "a" });
        tinst.Add(Vocab.I61_goto, new Inst { s = "b", m = 83 });
        tinst.Add(Vocab.I62_program_indirect, new Inst { s = "i" });
        tinst.Add(Vocab.I63_exchange_indirect, new Inst { s = "i" });
        tinst.Add(Vocab.I64_product_indirect, new Inst { s = "i", i = true });
        tinst.Add(Vocab.I65_multiply, new Inst { s = "a" });
        tinst.Add(Vocab.I66_pause, new Inst { s = "a" });
        tinst.Add(Vocab.I67_x_equals_t, new Inst { s = "b", i = true });
        tinst.Add(Vocab.I68_nop, new Inst { s = "a" });
        tinst.Add(Vocab.I69_operation, new Inst { s = "di", m = 84 });
        tinst.Add(Vocab.I70_radians, new Inst { s = "a" });
        tinst.Add(Vocab.I71_subroutine, new Inst { s = "b", i = true });
        tinst.Add(Vocab.I72_store_indirect, new Inst { s = "i" });
        tinst.Add(Vocab.I73_recall_indirect, new Inst { s = "i" });
        tinst.Add(Vocab.I74_sum_indirect, new Inst { s = "i", i = true });
        tinst.Add(Vocab.I75_subtract, new Inst { s = "a" });
        tinst.Add(Vocab.I76_label, new Inst { s = "m" });
        tinst.Add(Vocab.I77_x_greater_or_equal_than_t, new Inst { s = "b" });
        tinst.Add(Vocab.I78_sigma_plus, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I79_average, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I80_grades, new Inst { s = "a" });
        tinst.Add(Vocab.I81_reset, new Inst { s = "a" });
        tinst.Add(Vocab.I82_hir, new Inst { s = "d" });
        tinst.Add(Vocab.I83_goto_indirect, new Inst { s = "i" });
        tinst.Add(Vocab.I84_operation_indirect, new Inst { s = "i" });
        tinst.Add(Vocab.I85_add, new Inst { s = "a" });
        tinst.Add(Vocab.I86_set_flag, new Inst { s = "di", i = true });
        tinst.Add(Vocab.I87_if_flag, new Inst { s = "idb", i = true });
        tinst.Add(Vocab.I88_dms, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I89_pi, new Inst { s = "a" });
        tinst.Add(Vocab.I90_list, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I91_run_stop, new Inst { s = "a" });
        tinst.Add(Vocab.I92_return, new Inst { s = "a" });
        tinst.Add(Vocab.I93_dot, new Inst { s = "a" });
        tinst.Add(Vocab.I94_change_sign, new Inst { s = "a" });
        tinst.Add(Vocab.I95_equals, new Inst { s = "a" });
        tinst.Add(Vocab.I96_write, new Inst { s = "a", i = true });
        tinst.Add(Vocab.I97_dsz, new Inst { s = "idb", i = true });
        tinst.Add(Vocab.I98_advance, new Inst { s = "a" });
        tinst.Add(Vocab.I99_print, new Inst { s = "a" });
    }
}
