[package]
name = "rfind"
description = "A Rust version of find/XFind/Search"
version = "1.0.1"
authors = ["Pierre Violent"]
edition = "2024"

[dependencies]
termcolor = "1.4.1"
myglob = { path = "../03_MyGlob/04_Iterator" }
trash = "5.2.2"
chrono = "0.4.40"
terminal_size = "0.4.2"
