// ExtactStandardForm
// Quick and dirty helper to extract instruction definitions from ti58.g4
// It's a list of list of strings, each list contains the first "official" representation of the statement,
// and alternate representations accepted by grammar
// Used during t58 program reformatting
//
// 2025-11-12   PV      First version, after a nightmare trying to get antlr4 recognize a quoted string that counld contain \'

using System;
using System.IO;
using System.Text;

namespace ExtractStandardForm;

internal sealed class Program
{
    static void Main(string[] args)
    {
        using var sr = new StreamReader(@"C:\Development\GitHub\Projects\11_TI5x\ti58.g4", Encoding.UTF8);
        using var sw = new StreamWriter(@"C:\Development\GitHub\Projects\11_TI5x\temp.cs", false, Encoding.UTF8);
        sw.WriteLine(@"// StandardInstructions
// Autogenerated file from ti58.g4 by ExtractStandardForm

using System.Collections.Generic;

namespace SimpleParser;

internal static class StandardInstructions
{
    internal static List<List<string>> Sill = [");

        for (; ; )
        {
            var line = sr.ReadLine();
            if (line == null)
                break;
            if (!line.StartsWith('I'))
                continue;

            line = line.Split("//")[0].Trim();
            line = line.Split(":")[1].Trim();
            line = line.Split(";")[0].Trim();

            var ts = line.Split(" | ");

            bool first = false;
            foreach (var s in ts)
            {
                if (!first)
                {
                    sw.Write("        [");
                    first = true;
                }
                else
                { sw.Write(", "); }

                string t = s.Trim()[1..^1].Replace("\\'", "'");
                Console.Write("‹" + t + "›\t");
                sw.Write("\"" + t + "\"");
            }
            sw.WriteLine("],");
            Console.WriteLine();
        }

        sw.WriteLine("    ];");
        sw.WriteLine("}");
    }
}
